CREATE TABLE `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(255) DEFAULT NULL,
  `password` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `age` INT(11) DEFAULT NULL,
  `sex` VARCHAR(255) DEFAULT NULL,
  `tel` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  KEY `id` (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4
